export { default as Header } from "@/components/home/header";
export { default as HeroSection } from "@/components/home/hero-section";
export { default as IntroSection } from "@/components/home/intro-section";
export { default as DepartmentsSection } from "@/components/home/departments-section";
export { default as DoctorsSection } from "@/components/home/doctors-section";
export { default as EventsSection } from "@/components/home/events-section";
export { default as InfoSection } from "@/components/home/info-section";
export { default as CtaSection } from "@/components/home/cta-section";
export { default as Footer } from "@/components/home/footer";
